apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
spec:
  project: prod-project

  source:
    repoURL: https://github.com/sravan-kumarc/argocd-helm-app
    targetRevision: main
    path: nginx-chart
    helm:
      valueFiles:
        - values/values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated: {}   # manual for prod
    syncOptions:
      - CreateNamespace=true
